# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlgEmpresa.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgEmpresa(object):
    def setupUi(self, dlgEmpresa):
        dlgEmpresa.setObjectName("dlgEmpresa")
        dlgEmpresa.setWindowModality(QtCore.Qt.WindowModal)
        dlgEmpresa.resize(400, 418)
        dlgEmpresa.setModal(True)
        self.gbEmpresa = QtWidgets.QGroupBox(dlgEmpresa)
        self.gbEmpresa.setGeometry(QtCore.QRect(10, 10, 381, 341))
        self.gbEmpresa.setObjectName("gbEmpresa")
        self.lblNombre = QtWidgets.QLabel(self.gbEmpresa)
        self.lblNombre.setGeometry(QtCore.QRect(20, 30, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(14)
        self.lblNombre.setFont(font)
        self.lblNombre.setObjectName("lblNombre")
        self.lblDireccion = QtWidgets.QLabel(self.gbEmpresa)
        self.lblDireccion.setGeometry(QtCore.QRect(20, 70, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(14)
        self.lblDireccion.setFont(font)
        self.lblDireccion.setObjectName("lblDireccion")
        self.lblTelefono = QtWidgets.QLabel(self.gbEmpresa)
        self.lblTelefono.setGeometry(QtCore.QRect(20, 110, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(14)
        self.lblTelefono.setFont(font)
        self.lblTelefono.setObjectName("lblTelefono")
        self.lblRfc = QtWidgets.QLabel(self.gbEmpresa)
        self.lblRfc.setGeometry(QtCore.QRect(20, 150, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(14)
        self.lblRfc.setFont(font)
        self.lblRfc.setObjectName("lblRfc")
        self.lblSerial = QtWidgets.QLabel(self.gbEmpresa)
        self.lblSerial.setGeometry(QtCore.QRect(20, 190, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(14)
        self.lblSerial.setFont(font)
        self.lblSerial.setObjectName("lblSerial")
        self.lblLogo = QtWidgets.QLabel(self.gbEmpresa)
        self.lblLogo.setGeometry(QtCore.QRect(20, 230, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(14)
        self.lblLogo.setFont(font)
        self.lblLogo.setObjectName("lblLogo")
        self.pbLogo = QtWidgets.QPushButton(self.gbEmpresa)
        self.pbLogo.setGeometry(QtCore.QRect(160, 240, 75, 81))
        self.pbLogo.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../img/icon_acercade64x64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbLogo.setIcon(icon)
        self.pbLogo.setIconSize(QtCore.QSize(64, 64))
        self.pbLogo.setAutoDefault(False)
        self.pbLogo.setObjectName("pbLogo")
        self.leNombre = QtWidgets.QLineEdit(self.gbEmpresa)
        self.leNombre.setGeometry(QtCore.QRect(160, 30, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(14)
        self.leNombre.setFont(font)
        self.leNombre.setMaxLength(40)
        self.leNombre.setObjectName("leNombre")
        self.leDireccion = QtWidgets.QLineEdit(self.gbEmpresa)
        self.leDireccion.setGeometry(QtCore.QRect(160, 70, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(14)
        self.leDireccion.setFont(font)
        self.leDireccion.setMaxLength(40)
        self.leDireccion.setObjectName("leDireccion")
        self.leTelefono = QtWidgets.QLineEdit(self.gbEmpresa)
        self.leTelefono.setGeometry(QtCore.QRect(160, 110, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(14)
        self.leTelefono.setFont(font)
        self.leTelefono.setMaxLength(40)
        self.leTelefono.setObjectName("leTelefono")
        self.leRFC = QtWidgets.QLineEdit(self.gbEmpresa)
        self.leRFC.setGeometry(QtCore.QRect(160, 150, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(14)
        self.leRFC.setFont(font)
        self.leRFC.setMaxLength(13)
        self.leRFC.setObjectName("leRFC")
        self.leSerial = QtWidgets.QLineEdit(self.gbEmpresa)
        self.leSerial.setGeometry(QtCore.QRect(160, 190, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(14)
        self.leSerial.setFont(font)
        self.leSerial.setMaxLength(10)
        self.leSerial.setObjectName("leSerial")
        self.pbCancelar = QtWidgets.QPushButton(dlgEmpresa)
        self.pbCancelar.setGeometry(QtCore.QRect(10, 370, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(14)
        self.pbCancelar.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../img/icon_cancelar32x32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbCancelar.setIcon(icon1)
        self.pbCancelar.setIconSize(QtCore.QSize(32, 32))
        self.pbCancelar.setAutoDefault(False)
        self.pbCancelar.setObjectName("pbCancelar")
        self.pbAceptar = QtWidgets.QPushButton(dlgEmpresa)
        self.pbAceptar.setGeometry(QtCore.QRect(240, 370, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(14)
        self.pbAceptar.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../img/icon_aceptar32x32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbAceptar.setIcon(icon2)
        self.pbAceptar.setIconSize(QtCore.QSize(32, 32))
        self.pbAceptar.setAutoDefault(True)
        self.pbAceptar.setObjectName("pbAceptar")

        self.retranslateUi(dlgEmpresa)
        QtCore.QMetaObject.connectSlotsByName(dlgEmpresa)
        dlgEmpresa.setTabOrder(self.leNombre, self.leDireccion)
        dlgEmpresa.setTabOrder(self.leDireccion, self.leTelefono)
        dlgEmpresa.setTabOrder(self.leTelefono, self.leRFC)
        dlgEmpresa.setTabOrder(self.leRFC, self.leSerial)
        dlgEmpresa.setTabOrder(self.leSerial, self.pbLogo)
        dlgEmpresa.setTabOrder(self.pbLogo, self.pbAceptar)
        dlgEmpresa.setTabOrder(self.pbAceptar, self.pbCancelar)

    def retranslateUi(self, dlgEmpresa):
        _translate = QtCore.QCoreApplication.translate
        dlgEmpresa.setWindowTitle(_translate("dlgEmpresa", "Empresa"))
        self.gbEmpresa.setTitle(_translate("dlgEmpresa", "Datos"))
        self.lblNombre.setText(_translate("dlgEmpresa", "Nombre:"))
        self.lblDireccion.setText(_translate("dlgEmpresa", "Dirección:"))
        self.lblTelefono.setText(_translate("dlgEmpresa", "Teléfono:"))
        self.lblRfc.setText(_translate("dlgEmpresa", "RFC:"))
        self.lblSerial.setText(_translate("dlgEmpresa", "Serial:"))
        self.lblLogo.setText(_translate("dlgEmpresa", "Logo:"))
        self.pbCancelar.setText(_translate("dlgEmpresa", "Cancelar"))
        self.pbAceptar.setText(_translate("dlgEmpresa", "Aceptar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlgEmpresa = QtWidgets.QDialog()
    ui = Ui_dlgEmpresa()
    ui.setupUi(dlgEmpresa)
    dlgEmpresa.show()
    sys.exit(app.exec_())
