# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlgUsuarios.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgUsuarios(object):
    def setupUi(self, dlgUsuarios):
        dlgUsuarios.setObjectName("dlgUsuarios")
        dlgUsuarios.setWindowModality(QtCore.Qt.ApplicationModal)
        dlgUsuarios.resize(770, 492)
        dlgUsuarios.setModal(True)
        self.gbUsuario = QtWidgets.QGroupBox(dlgUsuarios)
        self.gbUsuario.setEnabled(False)
        self.gbUsuario.setGeometry(QtCore.QRect(10, 10, 750, 60))
        self.gbUsuario.setObjectName("gbUsuario")
        self.lblIdentificacion = QtWidgets.QLabel(self.gbUsuario)
        self.lblIdentificacion.setGeometry(QtCore.QRect(20, 20, 135, 30))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setPointSize(14)
        self.lblIdentificacion.setFont(font)
        self.lblIdentificacion.setObjectName("lblIdentificacion")
        self.leIdentificacion = QtWidgets.QLineEdit(self.gbUsuario)
        self.leIdentificacion.setGeometry(QtCore.QRect(170, 20, 190, 30))
        self.leIdentificacion.setObjectName("leIdentificacion")
        self.lblUsuarios = QtWidgets.QLabel(self.gbUsuario)
        self.lblUsuarios.setGeometry(QtCore.QRect(390, 20, 135, 30))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setPointSize(14)
        self.lblUsuarios.setFont(font)
        self.lblUsuarios.setObjectName("lblUsuarios")
        self.cboUsuarios = QtWidgets.QComboBox(self.gbUsuario)
        self.cboUsuarios.setGeometry(QtCore.QRect(540, 20, 190, 30))
        self.cboUsuarios.setObjectName("cboUsuarios")
        self.gbDetalle = QtWidgets.QGroupBox(dlgUsuarios)
        self.gbDetalle.setGeometry(QtCore.QRect(10, 80, 750, 321))
        self.gbDetalle.setObjectName("gbDetalle")
        self.lblPassword = QtWidgets.QLabel(self.gbDetalle)
        self.lblPassword.setGeometry(QtCore.QRect(20, 30, 135, 30))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setPointSize(14)
        self.lblPassword.setFont(font)
        self.lblPassword.setObjectName("lblPassword")
        self.lePassword = QtWidgets.QLineEdit(self.gbDetalle)
        self.lePassword.setGeometry(QtCore.QRect(170, 30, 190, 30))
        self.lePassword.setObjectName("lePassword")
        self.lblConfirmar = QtWidgets.QLabel(self.gbDetalle)
        self.lblConfirmar.setGeometry(QtCore.QRect(390, 30, 135, 30))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setPointSize(14)
        self.lblConfirmar.setFont(font)
        self.lblConfirmar.setObjectName("lblConfirmar")
        self.leConfirmar = QtWidgets.QLineEdit(self.gbDetalle)
        self.leConfirmar.setGeometry(QtCore.QRect(540, 30, 190, 30))
        self.leConfirmar.setObjectName("leConfirmar")
        self.lblNombre = QtWidgets.QLabel(self.gbDetalle)
        self.lblNombre.setGeometry(QtCore.QRect(20, 70, 135, 30))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setPointSize(14)
        self.lblNombre.setFont(font)
        self.lblNombre.setObjectName("lblNombre")
        self.leNombre = QtWidgets.QLineEdit(self.gbDetalle)
        self.leNombre.setGeometry(QtCore.QRect(170, 70, 560, 30))
        self.leNombre.setObjectName("leNombre")
        self.lblRol = QtWidgets.QLabel(self.gbDetalle)
        self.lblRol.setGeometry(QtCore.QRect(20, 110, 135, 30))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setPointSize(14)
        self.lblRol.setFont(font)
        self.lblRol.setObjectName("lblRol")
        self.leRol = QtWidgets.QLineEdit(self.gbDetalle)
        self.leRol.setGeometry(QtCore.QRect(170, 110, 190, 30))
        self.leRol.setObjectName("leRol")
        self.lblRoles = QtWidgets.QLabel(self.gbDetalle)
        self.lblRoles.setGeometry(QtCore.QRect(390, 110, 135, 30))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setPointSize(14)
        self.lblRoles.setFont(font)
        self.lblRoles.setObjectName("lblRoles")
        self.cboRoles = QtWidgets.QComboBox(self.gbDetalle)
        self.cboRoles.setGeometry(QtCore.QRect(540, 110, 190, 30))
        self.cboRoles.setObjectName("cboRoles")
        self.gbProcesos = QtWidgets.QGroupBox(self.gbDetalle)
        self.gbProcesos.setGeometry(QtCore.QRect(20, 150, 711, 161))
        self.gbProcesos.setObjectName("gbProcesos")
        self.listProcesos = QtWidgets.QListWidget(self.gbProcesos)
        self.listProcesos.setGeometry(QtCore.QRect(10, 20, 691, 131))
        self.listProcesos.setObjectName("listProcesos")
        self.groupBox = QtWidgets.QGroupBox(dlgUsuarios)
        self.groupBox.setGeometry(QtCore.QRect(10, 410, 391, 71))
        self.groupBox.setObjectName("groupBox")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(10, 20, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../img/icon_insertar32x32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(32, 32))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 20, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../img/icon_editar32x32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(270, 20, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setPointSize(14)
        self.pushButton_3.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../img/icon_eliminar32x32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_3.setObjectName("pushButton_3")
        self.groupBox_2 = QtWidgets.QGroupBox(dlgUsuarios)
        self.groupBox_2.setGeometry(QtCore.QRect(420, 410, 341, 71))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 20, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setPointSize(14)
        self.pushButton_4.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../img/icon_cancelar32x32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon3)
        self.pushButton_4.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_5.setGeometry(QtCore.QRect(180, 20, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setPointSize(14)
        self.pushButton_5.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../img/icon_aceptar32x32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon4)
        self.pushButton_5.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_5.setObjectName("pushButton_5")

        self.retranslateUi(dlgUsuarios)
        QtCore.QMetaObject.connectSlotsByName(dlgUsuarios)

    def retranslateUi(self, dlgUsuarios):
        _translate = QtCore.QCoreApplication.translate
        dlgUsuarios.setWindowTitle(_translate("dlgUsuarios", "Sistema - Usuarios"))
        self.gbUsuario.setTitle(_translate("dlgUsuarios", "Usuario"))
        self.lblIdentificacion.setText(_translate("dlgUsuarios", "Identificación:"))
        self.lblUsuarios.setText(_translate("dlgUsuarios", "Usuarios:"))
        self.gbDetalle.setTitle(_translate("dlgUsuarios", "Detalle"))
        self.lblPassword.setText(_translate("dlgUsuarios", "Password:"))
        self.lblConfirmar.setText(_translate("dlgUsuarios", "Confirmar:"))
        self.lblNombre.setText(_translate("dlgUsuarios", "Nombre:"))
        self.lblRol.setText(_translate("dlgUsuarios", "Rol:"))
        self.lblRoles.setText(_translate("dlgUsuarios", "Roles:"))
        self.gbProcesos.setTitle(_translate("dlgUsuarios", "Procesos"))
        self.groupBox.setTitle(_translate("dlgUsuarios", "Operaciones"))
        self.pushButton.setText(_translate("dlgUsuarios", "Ins"))
        self.pushButton_2.setText(_translate("dlgUsuarios", "Edit"))
        self.pushButton_3.setText(_translate("dlgUsuarios", "Elim"))
        self.groupBox_2.setTitle(_translate("dlgUsuarios", "Transacción"))
        self.pushButton_4.setText(_translate("dlgUsuarios", "Cancelar"))
        self.pushButton_5.setText(_translate("dlgUsuarios", "Aceptar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlgUsuarios = QtWidgets.QDialog()
    ui = Ui_dlgUsuarios()
    ui.setupUi(dlgUsuarios)
    dlgUsuarios.show()
    sys.exit(app.exec_())
